  - name: disabling the default redis version
    ansible.builtin.command: dnf module disable redis -y

  - name: enabling the redis 7 version
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: Installing redis
    ansible.builtin.package:
      name: redis
      state: installed
    
  - name: Update port number to accept remote connection and protected mode from yes to node
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: update protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'

  - name: start and enable service
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
      