  - name: nodejs setup
    include_role:
      name: common
      tasks_from: nodejs

  - name: app setup
    include_role:
      name: common
      tasks_from: appsetup

  - name: systemd setup
    include_role:
      name: common
      tasks_from: systemsetup




