  - name: Disabling default nginx version
    ansible.builtin.command: dnf module disable nginx -y

  - name: Enabling required nginx version
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: Installing Nginx server
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: start and enable nginx
    ansible.builtin.systemd_service:
      name: nginx
      state: started
      enabled: yes

  - name: Removing the html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Creating the html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download frontend content
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: Unzipping the frontend content
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: Removing default nginx file
    ansible.builtin.file:
      dest: /etc/nginx/nginx.conf
      state: absent

  - name: Copying nginx configuration file
    ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: 
      - Restart nginx



