- name: Stop the {{ component }} server
  tags:
    deployment
  ansible.builtin.service:
    name: catalogue
    state: stopped

- name: removing /app directory
  tags:
    deployment
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating /app directory
  tags:
    deployment
  ansible.builtin.file:
    path: /app
    state: directory

- name: downloading and unzipping the code
  # tags:
  #   deployment
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v{{ app_version }}.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app

- name: Restart {{ component }}
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted

