  - name: Installing Maven
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - maven
    - mysql

  - name: Installing cryptography and PyMySQL
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

    - name: Download maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app 