  - name: Disabling Nodejs default version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enabling Nodejs version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Installing Nodejs
    ansible.builtin.package: 
      name: nodejs
      state: installed

  - name: Install dependencies
    community.general.npm:
      path: /app